on: push
name: Build and deploy on push
jobs:
  zolaDeploy:
    name: zola deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - name: zola deploy
      uses: shalzz/zola-deploy-action@main
      env:
        PAGES_BRANCH: main
        TOKEN: ${{ secrets.TOKEN }}
